[install]
is_configured = 0

[ui]
is_visible = 1
label = VMware Vision for Splunk

[launcher]
author = Majid Ershadi
description = VMware lifecycle, configuration changes, users, alarms and syslog coverage
version = 1.1.1

[package]
id = vmware_vision
check_for_updates = true
