[vmware_vision_events]
search = sourcetype=vmware:vision:*
description = VMware Vision syslog

[vmware_vision_authentication]
search = sourcetype=vmware:vision:* cim_dataset=Authentication record_kind=event parser_status=mapped action IN (success,failure)

[vmware_vision_change]
search = sourcetype=vmware:vision:* cim_dataset=Change record_kind=event parser_status=mapped status IN (success,failure)
